name: kit_de_camaras2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^1.0.0
  supabase_flutter: ^0.2.5  # Asegúrate de usar la última versión
  carousel_slider: ^5.0.0
  url_launcher: ^6.1.9
  font_awesome_flutter: ^10.0.0  # Usa la versión más reciente compatible

  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/1.webp
    - assets/images/2.webp
    - assets/images/3.webp
    - assets/images/4.webp
    - assets/images/5.webp
    - assets/images/6.webp
    - assets/images/7.webp
    - assets/images/8.webp
    - assets/images/9.webp
    - assets/images/10.webp
    - assets/images/11.webp
    - assets/images/12.webp
    - assets/images/13.webp
    - assets/images/14.webp
    - assets/images/15.webp
    - assets/images/16.webp
    - assets/images/17.webp
    - assets/images/18.webp
    - assets/images/19.webp
    - assets/images/20.webp
    - assets/images/21.webp
    - assets/images/22.webp
    - assets/images/23.webp
    - assets/images/24.webp

    
    # Puedes añadir más imágenes si es necesario
